--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/TestPluginVOsaka
build-by-default: true
branches:
- main
projects:
  TestPluginVOsaka:
    libs:
      - src: VennDev/VOsaka/VOsaka
        version: ^1.0.1
      - src: VennDev/VOsakaComeToPMMP/VOsakaComeToPMMP
        version: ^1.0.0
...
